export default const oilInfo = [
  {
    "id":1,
    "name":"Abyssinian Oil",
    "sap":{
      "koh":0.168,
      "naoh":0.12
    },
    "oilProperties":{
      "iodine":98,
      "ins":70,
      "lauric":0,
      "myristic":0,
      "palmitic":3,
      "stearic":2,
      "ricinoleic":0,
      "oleic":18,
      "linoleic":11,
      "linolenic":4
    }
  },
  {
    "id":2,
    "name":"Almond Butter",
    "sap":{
      "koh":0.188,
      "naoh":0.134
    },
    "oilProperties":{
      "iodine":70,
      "ins":118,
      "lauric":0,
      "myristic":1,
      "palmitic":9,
      "stearic":15,
      "ricinoleic":0,
      "oleic":58,
      "linoleic":16,
      "linolenic":0
    }
  },
  {
    "id":3,
    "name":"Almond Oil, sweet",
    "sap":{
      "koh":0.195,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":99,
      "ins":97,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":0,
      "ricinoleic":0,
      "oleic":71,
      "linoleic":18,
      "linolenic":0
    }
  },
  {
    "id":4,
    "name":"Aloe Butter",
    "sap":{
      "koh":0.24,
      "naoh":0.171
    },
    "oilProperties":{
      "iodine":9,
      "ins":241,
      "lauric":45,
      "myristic":18,
      "palmitic":8,
      "stearic":3,
      "ricinoleic":0,
      "oleic":7,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":5,
    "name":"Andiroba Oil,karaba,crabwood",
    "sap":{
      "koh":0.188,
      "naoh":0.134
    },
    "oilProperties":{
      "iodine":68,
      "ins":120,
      "lauric":0,
      "myristic":0,
      "palmitic":28,
      "stearic":8,
      "ricinoleic":0,
      "oleic":51,
      "linoleic":9,
      "linolenic":0
    }
  },
  {
    "id":6,
    "name":"Apricot Kernal Oil",
    "sap":{
      "koh":0.195,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":100,
      "ins":91,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":0,
      "ricinoleic":0,
      "oleic":66,
      "linoleic":27,
      "linolenic":0
    }
  },
  {
    "id":7,
    "name":"Argan Oil",
    "sap":{
      "koh":0.191,
      "naoh":0.136
    },
    "oilProperties":{
      "iodine":95,
      "ins":95,
      "lauric":0,
      "myristic":1,
      "palmitic":14,
      "stearic":0,
      "ricinoleic":0,
      "oleic":46,
      "linoleic":34,
      "linolenic":1
    }
  },
  {
    "id":8,
    "name":"Avocado butter",
    "sap":{
      "koh":0.187,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":67,
      "ins":120,
      "lauric":0,
      "myristic":0,
      "palmitic":21,
      "stearic":10,
      "ricinoleic":0,
      "oleic":53,
      "linoleic":6,
      "linolenic":2
    }
  },
  {
    "id":9,
    "name":"Avocado Oil",
    "sap":{
      "koh":0.186,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":86,
      "ins":99,
      "lauric":0,
      "myristic":0,
      "palmitic":20,
      "stearic":2,
      "ricinoleic":0,
      "oleic":58,
      "linoleic":12,
      "linolenic":0
    }
  },
  {
    "id":10,
    "name":"Babassu Oil",
    "sap":{
      "koh":0.245,
      "naoh":0.175
    },
    "oilProperties":{
      "iodine":15,
      "ins":230,
      "lauric":50,
      "myristic":20,
      "palmitic":11,
      "stearic":4,
      "ricinoleic":0,
      "oleic":10,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":11,
    "name":"Baobab Oil",
    "sap":{
      "koh":0.2,
      "naoh":0.143
    },
    "oilProperties":{
      "iodine":75,
      "ins":125,
      "lauric":0,
      "myristic":1,
      "palmitic":24,
      "stearic":4,
      "ricinoleic":0,
      "oleic":37,
      "linoleic":28,
      "linolenic":2
    }
  },
  {
    "id":12,
    "name":"Beeswax",
    "sap":{
      "koh":0.094,
      "naoh":0.067
    },
    "oilProperties":{
      "iodine":10,
      "ins":84,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":13,
    "name":"Black Cumin Seed Oil, nigella sativa",
    "sap":{
      "koh":0.195,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":133,
      "ins":62,
      "lauric":0,
      "myristic":0,
      "palmitic":13,
      "stearic":3,
      "ricinoleic":0,
      "oleic":22,
      "linoleic":60,
      "linolenic":1
    }
  },
  {
    "id":14,
    "name":"Black Current Seed Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":178,
      "ins":12,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":2,
      "ricinoleic":0,
      "oleic":13,
      "linoleic":46,
      "linolenic":29
    }
  },
  {
    "id":15,
    "name":"Borage Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":135,
      "ins":55,
      "lauric":0,
      "myristic":0,
      "palmitic":10,
      "stearic":4,
      "ricinoleic":0,
      "oleic":20,
      "linoleic":43,
      "linolenic":5
    }
  },
  {
    "id":16,
    "name":"Brazil Nut Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":100,
      "ins":90,
      "lauric":0,
      "myristic":0,
      "palmitic":13,
      "stearic":11,
      "ricinoleic":0,
      "oleic":39,
      "linoleic":36,
      "linolenic":0
    }
  },
  {
    "id":17,
    "name":"Broccoli Seed Oil, Brassica Oleracea",
    "sap":{
      "koh":0.172,
      "naoh":0.123
    },
    "oilProperties":{
      "iodine":105,
      "ins":67,
      "lauric":0,
      "myristic":0,
      "palmitic":3,
      "stearic":1,
      "ricinoleic":0,
      "oleic":14,
      "linoleic":11,
      "linolenic":9
    }
  },
  {
    "id":18,
    "name":"Buriti Oil",
    "sap":{
      "koh":0.223,
      "naoh":0.159
    },
    "oilProperties":{
      "iodine":70,
      "ins":153,
      "lauric":0,
      "myristic":0,
      "palmitic":17,
      "stearic":2,
      "ricinoleic":0,
      "oleic":71,
      "linoleic":7,
      "linolenic":1
    }
  },
  {
    "id":19,
    "name":"Camelina Seed Oil",
    "sap":{
      "koh":0.188,
      "naoh":0.134
    },
    "oilProperties":{
      "iodine":144,
      "ins":44,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":2,
      "ricinoleic":0,
      "oleic":24,
      "linoleic":19,
      "linolenic":45
    }
  },
  {
    "id":20,
    "name":"Camellia Oil, Tea Seed",
    "sap":{
      "koh":0.193,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":78,
      "ins":115,
      "lauric":0,
      "myristic":0,
      "palmitic":9,
      "stearic":2,
      "ricinoleic":0,
      "oleic":77,
      "linoleic":8,
      "linolenic":0
    }
  },
  {
    "id":21,
    "name":"Candelilla Wax",
    "sap":{
      "koh":0.044,
      "naoh":0.031
    },
    "oilProperties":{
      "iodine":32,
      "ins":12,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":22,
    "name":"Canola Oil",
    "sap":{
      "koh":0.186,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":110,
      "ins":56,
      "lauric":0,
      "myristic":0,
      "palmitic":4,
      "stearic":2,
      "ricinoleic":0,
      "oleic":61,
      "linoleic":21,
      "linolenic":9
    }
  },
  {
    "id":23,
    "name":"Canola Oil, high oleic",
    "sap":{
      "koh":0.186,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":96,
      "ins":90,
      "lauric":0,
      "myristic":0,
      "palmitic":4,
      "stearic":2,
      "ricinoleic":0,
      "oleic":74,
      "linoleic":12,
      "linolenic":4
    }
  },
  {
    "id":24,
    "name":"Carrot Seed Oil, cold pressed",
    "sap":{
      "koh":0.144,
      "naoh":0.103
    },
    "oilProperties":{
      "iodine":56,
      "ins":0,
      "lauric":0,
      "myristic":0,
      "palmitic":4,
      "stearic":0,
      "ricinoleic":0,
      "oleic":80,
      "linoleic":13,
      "linolenic":0
    }
  },
  {
    "id":25,
    "name":"Castor Oil",
    "sap":{
      "koh":0.18,
      "naoh":0.128
    },
    "oilProperties":{
      "iodine":86,
      "ins":95,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":90,
      "oleic":4,
      "linoleic":4,
      "linolenic":0
    }
  },
  {
    "id":26,
    "name":"Cherry Kern1 Oil, p. avium",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":128,
      "ins":62,
      "lauric":0,
      "myristic":0,
      "palmitic":8,
      "stearic":3,
      "ricinoleic":0,
      "oleic":31,
      "linoleic":45,
      "linolenic":11
    }
  },
  {
    "id":27,
    "name":"Cherry Kern2 Oil, p. cerasus",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":118,
      "ins":74,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":3,
      "ricinoleic":0,
      "oleic":50,
      "linoleic":40,
      "linolenic":0
    }
  },
  {
    "id":28,
    "name":"Chicken Fat",
    "sap":{
      "koh":0.195,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":69,
      "ins":130,
      "lauric":0,
      "myristic":1,
      "palmitic":25,
      "stearic":7,
      "ricinoleic":0,
      "oleic":38,
      "linoleic":21,
      "linolenic":0
    }
  },
  {
    "id":29,
    "name":"Cocoa Butter",
    "sap":{
      "koh":0.194,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":37,
      "ins":157,
      "lauric":0,
      "myristic":0,
      "palmitic":28,
      "stearic":33,
      "ricinoleic":0,
      "oleic":35,
      "linoleic":3,
      "linolenic":0
    }
  },
  {
    "id":30,
    "name":"Coconut Oil, 76 deg",
    "sap":{
      "koh":0.257,
      "naoh":0.183
    },
    "oilProperties":{
      "iodine":10,
      "ins":258,
      "lauric":48,
      "myristic":19,
      "palmitic":9,
      "stearic":3,
      "ricinoleic":0,
      "oleic":8,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":31,
    "name":"Coconut Oil, 92 deg",
    "sap":{
      "koh":0.257,
      "naoh":0.183
    },
    "oilProperties":{
      "iodine":3,
      "ins":258,
      "lauric":48,
      "myristic":19,
      "palmitic":9,
      "stearic":3,
      "ricinoleic":0,
      "oleic":8,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":32,
    "name":"Coconut Oil, fractionated",
    "sap":{
      "koh":0.325,
      "naoh":0.232
    },
    "oilProperties":{
      "iodine":1,
      "ins":324,
      "lauric":2,
      "myristic":1,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":33,
    "name":"Coffee Bean Oil, green",
    "sap":{
      "koh":0.185,
      "naoh":0.132
    },
    "oilProperties":{
      "iodine":85,
      "ins":100,
      "lauric":0,
      "myristic":0,
      "palmitic":38,
      "stearic":8,
      "ricinoleic":0,
      "oleic":9,
      "linoleic":39,
      "linolenic":2
    }
  },
  {
    "id":34,
    "name":"Coffee Bean Oil, roasted",
    "sap":{
      "koh":0.18,
      "naoh":0.128
    },
    "oilProperties":{
      "iodine":87,
      "ins":93,
      "lauric":0,
      "myristic":0,
      "palmitic":40,
      "stearic":0,
      "ricinoleic":0,
      "oleic":8,
      "linoleic":38,
      "linolenic":2
    }
  },
  {
    "id":35,
    "name":"Cohune Oil",
    "sap":{
      "koh":0.205,
      "naoh":0.146
    },
    "oilProperties":{
      "iodine":30,
      "ins":175,
      "lauric":51,
      "myristic":13,
      "palmitic":8,
      "stearic":3,
      "ricinoleic":0,
      "oleic":18,
      "linoleic":3,
      "linolenic":0
    }
  },
  {
    "id":36,
    "name":"Corn Oil",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":117,
      "ins":69,
      "lauric":0,
      "myristic":0,
      "palmitic":12,
      "stearic":2,
      "ricinoleic":0,
      "oleic":32,
      "linoleic":51,
      "linolenic":1
    }
  },
  {
    "id":37,
    "name":"Cottonseed Oil",
    "sap":{
      "koh":0.194,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":108,
      "ins":89,
      "lauric":0,
      "myristic":0,
      "palmitic":13,
      "stearic":13,
      "ricinoleic":0,
      "oleic":18,
      "linoleic":52,
      "linolenic":1
    }
  },
  {
    "id":38,
    "name":"Cranberry Seed Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":150,
      "ins":40,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":2,
      "ricinoleic":0,
      "oleic":23,
      "linoleic":37,
      "linolenic":32
    }
  },
  {
    "id":39,
    "name":"Crisco, new w/palm",
    "sap":{
      "koh":0.193,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":111,
      "ins":82,
      "lauric":0,
      "myristic":0,
      "palmitic":20,
      "stearic":5,
      "ricinoleic":0,
      "oleic":28,
      "linoleic":40,
      "linolenic":6
    }
  },
  {
    "id":40,
    "name":"Crisco, old",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":93,
      "ins":115,
      "lauric":0,
      "myristic":0,
      "palmitic":13,
      "stearic":13,
      "ricinoleic":0,
      "oleic":18,
      "linoleic":52,
      "linolenic":0
    }
  },
  {
    "id":41,
    "name":"Cupuacu Butter",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":39,
      "ins":153,
      "lauric":0,
      "myristic":0,
      "palmitic":8,
      "stearic":35,
      "ricinoleic":0,
      "oleic":42,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":42,
    "name":"Duck Fat, flesh and skin",
    "sap":{
      "koh":0.194,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":72,
      "ins":122,
      "lauric":0,
      "myristic":1,
      "palmitic":26,
      "stearic":9,
      "ricinoleic":0,
      "oleic":44,
      "linoleic":13,
      "linolenic":1
    }
  },
  {
    "id":43,
    "name":"Emu Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":60,
      "ins":128,
      "lauric":0,
      "myristic":0,
      "palmitic":23,
      "stearic":9,
      "ricinoleic":0,
      "oleic":47,
      "linoleic":8,
      "linolenic":0
    }
  },
  {
    "id":44,
    "name":"Evening Primrose Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":160,
      "ins":30,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":80,
      "linolenic":9
    }
  },
  {
    "id":45,
    "name":"Flax Oil, linseed",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":180,
      "ins":-6,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":3,
      "ricinoleic":0,
      "oleic":27,
      "linoleic":13,
      "linolenic":50
    }
  },
  {
    "id":46,
    "name":"Ghee, any bovine",
    "sap":{
      "koh":0.227,
      "naoh":0.162
    },
    "oilProperties":{
      "iodine":30,
      "ins":191,
      "lauric":4,
      "myristic":11,
      "palmitic":28,
      "stearic":12,
      "ricinoleic":0,
      "oleic":19,
      "linoleic":2,
      "linolenic":1
    }
  },
  {
    "id":47,
    "name":"Goose Fat",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":65,
      "ins":130,
      "lauric":0,
      "myristic":0,
      "palmitic":21,
      "stearic":6,
      "ricinoleic":0,
      "oleic":54,
      "linoleic":10,
      "linolenic":0
    }
  },
  {
    "id":48,
    "name":"Grapeseed Oil",
    "sap":{
      "koh":0.181,
      "naoh":0.129
    },
    "oilProperties":{
      "iodine":131,
      "ins":66,
      "lauric":0,
      "myristic":0,
      "palmitic":8,
      "stearic":4,
      "ricinoleic":0,
      "oleic":20,
      "linoleic":68,
      "linolenic":0
    }
  },
  {
    "id":49,
    "name":"Hazelnut Oil",
    "sap":{
      "koh":0.195,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":97,
      "ins":94,
      "lauric":0,
      "myristic":0,
      "palmitic":5,
      "stearic":3,
      "ricinoleic":0,
      "oleic":75,
      "linoleic":10,
      "linolenic":0
    }
  },
  {
    "id":50,
    "name":"Hemp Oil",
    "sap":{
      "koh":0.193,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":165,
      "ins":39,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":2,
      "ricinoleic":0,
      "oleic":12,
      "linoleic":57,
      "linolenic":21
    }
  },
  {
    "id":51,
    "name":"Horse Oil",
    "sap":{
      "koh":0.196,
      "naoh":0.14
    },
    "oilProperties":{
      "iodine":79,
      "ins":117,
      "lauric":0,
      "myristic":3,
      "palmitic":26,
      "stearic":5,
      "ricinoleic":0,
      "oleic":10,
      "linoleic":20,
      "linolenic":19
    }
  },
  {
    "id":52,
    "name":"Illipe Butter",
    "sap":{
      "koh":0.185,
      "naoh":0.132
    },
    "oilProperties":{
      "iodine":33,
      "ins":152,
      "lauric":0,
      "myristic":0,
      "palmitic":17,
      "stearic":45,
      "ricinoleic":0,
      "oleic":35,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":53,
    "name":"Japan Wax",
    "sap":{
      "koh":0.215,
      "naoh":0.153
    },
    "oilProperties":{
      "iodine":11,
      "ins":204,
      "lauric":0,
      "myristic":1,
      "palmitic":80,
      "stearic":7,
      "ricinoleic":0,
      "oleic":4,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":54,
    "name":"Jatropha Oil, soapnut seed oil",
    "sap":{
      "koh":0.193,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":102,
      "ins":91,
      "lauric":0,
      "myristic":0,
      "palmitic":9,
      "stearic":7,
      "ricinoleic":0,
      "oleic":44,
      "linoleic":34,
      "linolenic":0
    }
  },
  {
    "id":55,
    "name":"Jojoba Oil (a Liquid Wax Ester)",
    "sap":{
      "koh":0.092,
      "naoh":0.066
    },
    "oilProperties":{
      "iodine":83,
      "ins":11,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":12,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":56,
    "name":"Karanja Oil",
    "sap":{
      "koh":0.183,
      "naoh":0.13
    },
    "oilProperties":{
      "iodine":85,
      "ins":98,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":6,
      "ricinoleic":0,
      "oleic":58,
      "linoleic":15,
      "linolenic":0
    }
  },
  {
    "id":57,
    "name":"Kokum Butter",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":35,
      "ins":155,
      "lauric":0,
      "myristic":0,
      "palmitic":4,
      "stearic":56,
      "ricinoleic":0,
      "oleic":36,
      "linoleic":1,
      "linolenic":0
    }
  },
  {
    "id":58,
    "name":"Kpangnan Butter",
    "sap":{
      "koh":0.191,
      "naoh":0.136
    },
    "oilProperties":{
      "iodine":42,
      "ins":149,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":44,
      "ricinoleic":0,
      "oleic":49,
      "linoleic":1,
      "linolenic":0
    }
  },
  {
    "id":59,
    "name":"Kukui nut Oil",
    "sap":{
      "koh":0.189,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":168,
      "ins":24,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":2,
      "ricinoleic":0,
      "oleic":20,
      "linoleic":42,
      "linolenic":29
    }
  },
  {
    "id":60,
    "name":"Lanolin liquid Wax",
    "sap":{
      "koh":0.106,
      "naoh":0.076
    },
    "oilProperties":{
      "iodine":27,
      "ins":83,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":61,
    "name":"Lard, Pig Tallow (Manteca)",
    "sap":{
      "koh":0.198,
      "naoh":0.141
    },
    "oilProperties":{
      "iodine":57,
      "ins":139,
      "lauric":0,
      "myristic":1,
      "palmitic":28,
      "stearic":13,
      "ricinoleic":0,
      "oleic":46,
      "linoleic":6,
      "linolenic":0
    }
  },
  {
    "id":62,
    "name":"Laurel Fruit Oil",
    "sap":{
      "koh":0.198,
      "naoh":0.141
    },
    "oilProperties":{
      "iodine":74,
      "ins":124,
      "lauric":25,
      "myristic":1,
      "palmitic":15,
      "stearic":1,
      "ricinoleic":0,
      "oleic":31,
      "linoleic":26,
      "linolenic":1
    }
  },
  {
    "id":63,
    "name":"Lauric Acid",
    "sap":{
      "koh":0.28,
      "naoh":0.2
    },
    "oilProperties":{
      "iodine":0,
      "ins":280,
      "lauric":99,
      "myristic":1,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":64,
    "name":"Linseed Oil, flax",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":180,
      "ins":-6,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":3,
      "ricinoleic":0,
      "oleic":27,
      "linoleic":13,
      "linolenic":50
    }
  },
  {
    "id":65,
    "name":"Loofa Seed Oil, Luffa cylinderica",
    "sap":{
      "koh":0.187,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":108,
      "ins":79,
      "lauric":0,
      "myristic":0,
      "palmitic":9,
      "stearic":18,
      "ricinoleic":0,
      "oleic":30,
      "linoleic":47,
      "linolenic":0
    }
  },
  {
    "id":66,
    "name":"Macadamia Nut Butter",
    "sap":{
      "koh":0.188,
      "naoh":0.134
    },
    "oilProperties":{
      "iodine":70,
      "ins":118,
      "lauric":0,
      "myristic":1,
      "palmitic":6,
      "stearic":12,
      "ricinoleic":0,
      "oleic":56,
      "linoleic":3,
      "linolenic":1
    }
  },
  {
    "id":67,
    "name":"Macadamia Nut Oil",
    "sap":{
      "koh":0.195,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":76,
      "ins":119,
      "lauric":0,
      "myristic":0,
      "palmitic":9,
      "stearic":5,
      "ricinoleic":0,
      "oleic":59,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":68,
    "name":"Mafura Butter, Trichilia emetica ",
    "sap":{
      "koh":0.198,
      "naoh":0.141
    },
    "oilProperties":{
      "iodine":66,
      "ins":132,
      "lauric":0,
      "myristic":1,
      "palmitic":37,
      "stearic":3,
      "ricinoleic":0,
      "oleic":49,
      "linoleic":11,
      "linolenic":1
    }
  },
  {
    "id":69,
    "name":"Mango Seed Butter",
    "sap":{
      "koh":0.191,
      "naoh":0.136
    },
    "oilProperties":{
      "iodine":45,
      "ins":146,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":42,
      "ricinoleic":0,
      "oleic":45,
      "linoleic":3,
      "linolenic":0
    }
  },
  {
    "id":70,
    "name":"Mango Seed Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":60,
      "ins":130,
      "lauric":0,
      "myristic":0,
      "palmitic":8,
      "stearic":27,
      "ricinoleic":0,
      "oleic":52,
      "linoleic":8,
      "linolenic":1
    }
  },
  {
    "id":71,
    "name":"Marula Oil",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":73,
      "ins":119,
      "lauric":0,
      "myristic":0,
      "palmitic":11,
      "stearic":7,
      "ricinoleic":0,
      "oleic":75,
      "linoleic":4,
      "linolenic":0
    }
  },
  {
    "id":72,
    "name":"Meadowfoam Oil",
    "sap":{
      "koh":0.169,
      "naoh":0.12
    },
    "oilProperties":{
      "iodine":92,
      "ins":77,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":73,
    "name":"Milk Fat, any bovine",
    "sap":{
      "koh":0.227,
      "naoh":0.162
    },
    "oilProperties":{
      "iodine":30,
      "ins":191,
      "lauric":4,
      "myristic":11,
      "palmitic":28,
      "stearic":12,
      "ricinoleic":0,
      "oleic":19,
      "linoleic":2,
      "linolenic":1
    }
  },
  {
    "id":74,
    "name":"Milk Thistle Oil",
    "sap":{
      "koh":0.196,
      "naoh":0.14
    },
    "oilProperties":{
      "iodine":115,
      "ins":81,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":2,
      "ricinoleic":0,
      "oleic":26,
      "linoleic":64,
      "linolenic":0
    }
  },
  {
    "id":75,
    "name":"Mink Oil",
    "sap":{
      "koh":0.196,
      "naoh":0.14
    },
    "oilProperties":{
      "iodine":55,
      "ins":141,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":76,
    "name":"Monoi de Tahiti  Oil",
    "sap":{
      "koh":0.255,
      "naoh":0.182
    },
    "oilProperties":{
      "iodine":9,
      "ins":246,
      "lauric":44,
      "myristic":16,
      "palmitic":10,
      "stearic":3,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":77,
    "name":"Moringa Oil",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":68,
      "ins":124,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":7,
      "ricinoleic":0,
      "oleic":71,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":78,
    "name":"Mowrah Butter",
    "sap":{
      "koh":0.194,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":62,
      "ins":132,
      "lauric":0,
      "myristic":0,
      "palmitic":24,
      "stearic":22,
      "ricinoleic":0,
      "oleic":36,
      "linoleic":15,
      "linolenic":0
    }
  },
  {
    "id":79,
    "name":"Murumuru Butter",
    "sap":{
      "koh":0.275,
      "naoh":0.196
    },
    "oilProperties":{
      "iodine":25,
      "ins":250,
      "lauric":47,
      "myristic":26,
      "palmitic":6,
      "stearic":3,
      "ricinoleic":0,
      "oleic":15,
      "linoleic":3,
      "linolenic":0
    }
  },
  {
    "id":80,
    "name":"Mustard Oil, kachi ghani",
    "sap":{
      "koh":0.173,
      "naoh":0.123
    },
    "oilProperties":{
      "iodine":101,
      "ins":72,
      "lauric":0,
      "myristic":0,
      "palmitic":2,
      "stearic":2,
      "ricinoleic":0,
      "oleic":18,
      "linoleic":14,
      "linolenic":9
    }
  },
  {
    "id":81,
    "name":"Myristic Acid",
    "sap":{
      "koh":0.247,
      "naoh":0.176
    },
    "oilProperties":{
      "iodine":1,
      "ins":246,
      "lauric":0,
      "myristic":99,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":82,
    "name":"Neatsfoot Oil",
    "sap":{
      "koh":0.18,
      "naoh":0.128
    },
    "oilProperties":{
      "iodine":90,
      "ins":90,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":83,
    "name":"Neem Seed Oil",
    "sap":{
      "koh":0.193,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":72,
      "ins":121,
      "lauric":0,
      "myristic":2,
      "palmitic":21,
      "stearic":16,
      "ricinoleic":0,
      "oleic":46,
      "linoleic":12,
      "linolenic":0
    }
  },
  {
    "id":84,
    "name":"Nutmeg Butter",
    "sap":{
      "koh":0.1624,
      "naoh":0.116
    },
    "oilProperties":{
      "iodine":46,
      "ins":116,
      "lauric":3,
      "myristic":83,
      "palmitic":4,
      "stearic":0,
      "ricinoleic":0,
      "oleic":5,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":85,
    "name":"Oat Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":104,
      "ins":86,
      "lauric":0,
      "myristic":0,
      "palmitic":15,
      "stearic":2,
      "ricinoleic":0,
      "oleic":40,
      "linoleic":39,
      "linolenic":0
    }
  },
  {
    "id":86,
    "name":"Oleic Acid",
    "sap":{
      "koh":0.202,
      "naoh":0.144
    },
    "oilProperties":{
      "iodine":92,
      "ins":110,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":99,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":87,
    "name":"Olive Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":85,
      "ins":105,
      "lauric":0,
      "myristic":0,
      "palmitic":14,
      "stearic":3,
      "ricinoleic":0,
      "oleic":69,
      "linoleic":12,
      "linolenic":1
    }
  },
  {
    "id":88,
    "name":"Olive Oil  pomace",
    "sap":{
      "koh":0.188,
      "naoh":0.134
    },
    "oilProperties":{
      "iodine":84,
      "ins":104,
      "lauric":0,
      "myristic":0,
      "palmitic":14,
      "stearic":3,
      "ricinoleic":0,
      "oleic":69,
      "linoleic":12,
      "linolenic":2
    }
  },
  {
    "id":89,
    "name":"Ostrich Oil",
    "sap":{
      "koh":0.1946,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":97,
      "ins":128,
      "lauric":3,
      "myristic":1,
      "palmitic":26,
      "stearic":6,
      "ricinoleic":0,
      "oleic":37,
      "linoleic":17,
      "linolenic":3
    }
  },
  {
    "id":90,
    "name":"Palm Kernel Oil",
    "sap":{
      "koh":0.247,
      "naoh":0.176
    },
    "oilProperties":{
      "iodine":20,
      "ins":227,
      "lauric":49,
      "myristic":16,
      "palmitic":8,
      "stearic":2,
      "ricinoleic":0,
      "oleic":15,
      "linoleic":3,
      "linolenic":0
    }
  },
  {
    "id":91,
    "name":"Palm Kernel Oil Flakes, hydrogenated",
    "sap":{
      "koh":0.247,
      "naoh":0.176
    },
    "oilProperties":{
      "iodine":20,
      "ins":227,
      "lauric":49,
      "myristic":17,
      "palmitic":8,
      "stearic":16,
      "ricinoleic":0,
      "oleic":4,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":92,
    "name":"Palm Oil",
    "sap":{
      "koh":0.199,
      "naoh":0.142
    },
    "oilProperties":{
      "iodine":53,
      "ins":145,
      "lauric":0,
      "myristic":1,
      "palmitic":44,
      "stearic":5,
      "ricinoleic":0,
      "oleic":39,
      "linoleic":10,
      "linolenic":0
    }
  },
  {
    "id":93,
    "name":"Palm Stearin",
    "sap":{
      "koh":0.199,
      "naoh":0.142
    },
    "oilProperties":{
      "iodine":48,
      "ins":151,
      "lauric":0,
      "myristic":2,
      "palmitic":60,
      "stearic":5,
      "ricinoleic":0,
      "oleic":26,
      "linoleic":7,
      "linolenic":0
    }
  },
  {
    "id":94,
    "name":"Palmitic Acid",
    "sap":{
      "koh":0.215,
      "naoh":0.153
    },
    "oilProperties":{
      "iodine":2,
      "ins":213,
      "lauric":0,
      "myristic":0,
      "palmitic":98,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":95,
    "name":"Palmolein",
    "sap":{
      "koh":0.2,
      "naoh":0.143
    },
    "oilProperties":{
      "iodine":58,
      "ins":142,
      "lauric":0,
      "myristic":1,
      "palmitic":40,
      "stearic":5,
      "ricinoleic":0,
      "oleic":43,
      "linoleic":11,
      "linolenic":0
    }
  },
  {
    "id":96,
    "name":"Papaya seed oil, Carica papaya",
    "sap":{
      "koh":0.158,
      "naoh":0.113
    },
    "oilProperties":{
      "iodine":67,
      "ins":91,
      "lauric":0,
      "myristic":0,
      "palmitic":13,
      "stearic":5,
      "ricinoleic":0,
      "oleic":76,
      "linoleic":3,
      "linolenic":0
    }
  },
  {
    "id":97,
    "name":"Passion Fruit Seed Oil",
    "sap":{
      "koh":0.183,
      "naoh":0.13
    },
    "oilProperties":{
      "iodine":136,
      "ins":47,
      "lauric":0,
      "myristic":0,
      "palmitic":10,
      "stearic":3,
      "ricinoleic":0,
      "oleic":15,
      "linoleic":70,
      "linolenic":1
    }
  },
  {
    "id":98,
    "name":"Pataua (Patawa) Oil",
    "sap":{
      "koh":0.2,
      "naoh":0.143
    },
    "oilProperties":{
      "iodine":77,
      "ins":123,
      "lauric":0,
      "myristic":0,
      "palmitic":13,
      "stearic":4,
      "ricinoleic":0,
      "oleic":78,
      "linoleic":3,
      "linolenic":1
    }
  },
  {
    "id":99,
    "name":"Peach Kernel Oil",
    "sap":{
      "koh":0.191,
      "naoh":0.136
    },
    "oilProperties":{
      "iodine":108,
      "ins":87,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":2,
      "ricinoleic":0,
      "oleic":65,
      "linoleic":25,
      "linolenic":1
    }
  },
  {
    "id":100,
    "name":"Peanut Oil",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":92,
      "ins":99,
      "lauric":0,
      "myristic":0,
      "palmitic":8,
      "stearic":3,
      "ricinoleic":0,
      "oleic":56,
      "linoleic":26,
      "linolenic":0
    }
  },
  {
    "id":101,
    "name":"Pecan Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":113,
      "ins":77,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":2,
      "ricinoleic":0,
      "oleic":50,
      "linoleic":39,
      "linolenic":2
    }
  },
  {
    "id":102,
    "name":"Perilla Seed Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":196,
      "ins":-6,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":2,
      "ricinoleic":0,
      "oleic":15,
      "linoleic":16,
      "linolenic":56
    }
  },
  {
    "id":103,
    "name":"Pine Tar, lye calc only no FA",
    "sap":{
      "koh":0.06,
      "naoh":0.043
    },
    "oilProperties":{
      "iodine":0,
      "ins":0,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":0,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":104,
    "name":"Pistachio Oil",
    "sap":{
      "koh":0.186,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":95,
      "ins":92,
      "lauric":0,
      "myristic":0,
      "palmitic":11,
      "stearic":1,
      "ricinoleic":0,
      "oleic":63,
      "linoleic":25,
      "linolenic":0
    }
  },
  {
    "id":105,
    "name":"Plum Kernel Oil",
    "sap":{
      "koh":0.194,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":98,
      "ins":96,
      "lauric":0,
      "myristic":0,
      "palmitic":3,
      "stearic":0,
      "ricinoleic":0,
      "oleic":68,
      "linoleic":23,
      "linolenic":0
    }
  },
  {
    "id":106,
    "name":"Pomegranate Seed Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":22,
      "ins":168,
      "lauric":0,
      "myristic":0,
      "palmitic":3,
      "stearic":3,
      "ricinoleic":0,
      "oleic":7,
      "linoleic":7,
      "linolenic":78
    }
  },
  {
    "id":107,
    "name":"Poppy Seed Oil",
    "sap":{
      "koh":0.194,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":140,
      "ins":54,
      "lauric":0,
      "myristic":0,
      "palmitic":10,
      "stearic":2,
      "ricinoleic":0,
      "oleic":17,
      "linoleic":69,
      "linolenic":2
    }
  },
  {
    "id":108,
    "name":"Pracaxi (Pracachy) Seed Oil - hair conditioner",
    "sap":{
      "koh":0.175,
      "naoh":0.125
    },
    "oilProperties":{
      "iodine":68,
      "ins":107,
      "lauric":1,
      "myristic":1,
      "palmitic":2,
      "stearic":2,
      "ricinoleic":0,
      "oleic":44,
      "linoleic":2,
      "linolenic":2
    }
  },
  {
    "id":109,
    "name":"Pumpkin Seed Oil virgin",
    "sap":{
      "koh":0.195,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":128,
      "ins":67,
      "lauric":0,
      "myristic":0,
      "palmitic":11,
      "stearic":8,
      "ricinoleic":0,
      "oleic":33,
      "linoleic":50,
      "linolenic":0
    }
  },
  {
    "id":110,
    "name":"Rabbit Fat",
    "sap":{
      "koh":0.201,
      "naoh":0.143
    },
    "oilProperties":{
      "iodine":85,
      "ins":116,
      "lauric":0,
      "myristic":3,
      "palmitic":30,
      "stearic":6,
      "ricinoleic":0,
      "oleic":30,
      "linoleic":20,
      "linolenic":5
    }
  },
  {
    "id":111,
    "name":"Rapeseed Oil, unrefined canola",
    "sap":{
      "koh":0.175,
      "naoh":0.125
    },
    "oilProperties":{
      "iodine":106,
      "ins":69,
      "lauric":0,
      "myristic":0,
      "palmitic":4,
      "stearic":1,
      "ricinoleic":0,
      "oleic":17,
      "linoleic":13,
      "linolenic":9
    }
  },
  {
    "id":112,
    "name":"Raspberry Seed Oil",
    "sap":{
      "koh":0.187,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":163,
      "ins":24,
      "lauric":0,
      "myristic":0,
      "palmitic":3,
      "stearic":0,
      "ricinoleic":0,
      "oleic":13,
      "linoleic":55,
      "linolenic":26
    }
  },
  {
    "id":113,
    "name":"Red Palm Butter",
    "sap":{
      "koh":0.199,
      "naoh":0.142
    },
    "oilProperties":{
      "iodine":53,
      "ins":145,
      "lauric":0,
      "myristic":1,
      "palmitic":44,
      "stearic":5,
      "ricinoleic":0,
      "oleic":39,
      "linoleic":10,
      "linolenic":0
    }
  },
  {
    "id":114,
    "name":"Rice Bran Oil, refined",
    "sap":{
      "koh":0.187,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":100,
      "ins":87,
      "lauric":0,
      "myristic":1,
      "palmitic":22,
      "stearic":3,
      "ricinoleic":0,
      "oleic":38,
      "linoleic":34,
      "linolenic":2
    }
  },
  {
    "id":115,
    "name":"Rosehip Oil",
    "sap":{
      "koh":0.187,
      "naoh":0.133
    },
    "oilProperties":{
      "iodine":188,
      "ins":10,
      "lauric":0,
      "myristic":0,
      "palmitic":4,
      "stearic":2,
      "ricinoleic":0,
      "oleic":12,
      "linoleic":46,
      "linolenic":31
    }
  },
  {
    "id":116,
    "name":"Sacha Inchi, Plukenetia volubilis",
    "sap":{
      "koh":0.188,
      "naoh":0.134
    },
    "oilProperties":{
      "iodine":141,
      "ins":47,
      "lauric":0,
      "myristic":0,
      "palmitic":4,
      "stearic":3,
      "ricinoleic":0,
      "oleic":10,
      "linoleic":35,
      "linolenic":48
    }
  },
  {
    "id":117,
    "name":"Safflower Oil",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":145,
      "ins":47,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":0,
      "ricinoleic":0,
      "oleic":15,
      "linoleic":75,
      "linolenic":0
    }
  },
  {
    "id":118,
    "name":"Safflower Oil, high oleic",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":93,
      "ins":97,
      "lauric":0,
      "myristic":0,
      "palmitic":5,
      "stearic":2,
      "ricinoleic":0,
      "oleic":77,
      "linoleic":15,
      "linolenic":0
    }
  },
  {
    "id":119,
    "name":"Sal Butter",
    "sap":{
      "koh":0.185,
      "naoh":0.132
    },
    "oilProperties":{
      "iodine":39,
      "ins":146,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":44,
      "ricinoleic":0,
      "oleic":40,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":120,
    "name":"Salmon Oil",
    "sap":{
      "koh":0.185,
      "naoh":0.132
    },
    "oilProperties":{
      "iodine":169,
      "ins":16,
      "lauric":0,
      "myristic":5,
      "palmitic":19,
      "stearic":2,
      "ricinoleic":0,
      "oleic":23,
      "linoleic":2,
      "linolenic":1
    }
  },
  {
    "id":121,
    "name":"Saw Palmetto Extract",
    "sap":{
      "koh":0.23,
      "naoh":0.164
    },
    "oilProperties":{
      "iodine":45,
      "ins":185,
      "lauric":29,
      "myristic":11,
      "palmitic":8,
      "stearic":2,
      "ricinoleic":0,
      "oleic":35,
      "linoleic":4,
      "linolenic":1
    }
  },
  {
    "id":122,
    "name":"Saw Palmetto Oil",
    "sap":{
      "koh":0.22,
      "naoh":0.157
    },
    "oilProperties":{
      "iodine":44,
      "ins":176,
      "lauric":29,
      "myristic":13,
      "palmitic":9,
      "stearic":2,
      "ricinoleic":0,
      "oleic":31,
      "linoleic":4,
      "linolenic":1
    }
  },
  {
    "id":123,
    "name":"Sea Buckthorn Oil, seed",
    "sap":{
      "koh":0.195,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":165,
      "ins":30,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":3,
      "ricinoleic":0,
      "oleic":14,
      "linoleic":36,
      "linolenic":38
    }
  },
  {
    "id":124,
    "name":"Sea Buckthorn Oil, seed and berry",
    "sap":{
      "koh":0.183,
      "naoh":0.13
    },
    "oilProperties":{
      "iodine":86,
      "ins":97,
      "lauric":0,
      "myristic":0,
      "palmitic":30,
      "stearic":1,
      "ricinoleic":0,
      "oleic":28,
      "linoleic":10,
      "linolenic":0
    }
  },
  {
    "id":125,
    "name":"Sesame Oil",
    "sap":{
      "koh":0.188,
      "naoh":0.134
    },
    "oilProperties":{
      "iodine":110,
      "ins":81,
      "lauric":0,
      "myristic":0,
      "palmitic":10,
      "stearic":5,
      "ricinoleic":0,
      "oleic":40,
      "linoleic":43,
      "linolenic":0
    }
  },
  {
    "id":126,
    "name":"Shea Butter",
    "sap":{
      "koh":0.179,
      "naoh":0.128
    },
    "oilProperties":{
      "iodine":59,
      "ins":116,
      "lauric":0,
      "myristic":0,
      "palmitic":5,
      "stearic":40,
      "ricinoleic":0,
      "oleic":48,
      "linoleic":6,
      "linolenic":0
    }
  },
  {
    "id":127,
    "name":"Shea Oil, fractionated",
    "sap":{
      "koh":0.185,
      "naoh":0.132
    },
    "oilProperties":{
      "iodine":83,
      "ins":102,
      "lauric":0,
      "myristic":0,
      "palmitic":6,
      "stearic":10,
      "ricinoleic":0,
      "oleic":73,
      "linoleic":11,
      "linolenic":0
    }
  },
  {
    "id":128,
    "name":"SoapQuick, conventional",
    "sap":{
      "koh":0.212,
      "naoh":0.151
    },
    "oilProperties":{
      "iodine":59,
      "ins":153,
      "lauric":13,
      "myristic":6,
      "palmitic":17,
      "stearic":3,
      "ricinoleic":5,
      "oleic":42,
      "linoleic":8,
      "linolenic":1
    }
  },
  {
    "id":129,
    "name":"SoapQuick, organic",
    "sap":{
      "koh":0.213,
      "naoh":0.152
    },
    "oilProperties":{
      "iodine":56,
      "ins":156,
      "lauric":13,
      "myristic":5,
      "palmitic":20,
      "stearic":3,
      "ricinoleic":0,
      "oleic":45,
      "linoleic":10,
      "linolenic":0
    }
  },
  {
    "id":130,
    "name":"Soybean Oil",
    "sap":{
      "koh":0.191,
      "naoh":0.136
    },
    "oilProperties":{
      "iodine":131,
      "ins":61,
      "lauric":0,
      "myristic":0,
      "palmitic":11,
      "stearic":5,
      "ricinoleic":0,
      "oleic":24,
      "linoleic":50,
      "linolenic":8
    }
  },
  {
    "id":131,
    "name":"Soybean, 27.5% hydrogenated",
    "sap":{
      "koh":0.191,
      "naoh":0.136
    },
    "oilProperties":{
      "iodine":78,
      "ins":113,
      "lauric":0,
      "myristic":0,
      "palmitic":9,
      "stearic":15,
      "ricinoleic":0,
      "oleic":41,
      "linoleic":7,
      "linolenic":1
    }
  },
  {
    "id":132,
    "name":"Soybean, fully hydrogenated (soy wax)",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":1,
      "ins":191,
      "lauric":0,
      "myristic":0,
      "palmitic":11,
      "stearic":87,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":133,
    "name":"Stearic Acid",
    "sap":{
      "koh":0.198,
      "naoh":0.141
    },
    "oilProperties":{
      "iodine":2,
      "ins":196,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":99,
      "ricinoleic":0,
      "oleic":0,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":134,
    "name":"Sunflower Oil",
    "sap":{
      "koh":0.189,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":133,
      "ins":63,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":4,
      "ricinoleic":0,
      "oleic":16,
      "linoleic":70,
      "linolenic":1
    }
  },
  {
    "id":135,
    "name":"Sunflower Oil, high oleic",
    "sap":{
      "koh":0.189,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":83,
      "ins":106,
      "lauric":0,
      "myristic":0,
      "palmitic":3,
      "stearic":4,
      "ricinoleic":0,
      "oleic":83,
      "linoleic":4,
      "linolenic":1
    }
  },
  {
    "id":136,
    "name":"Tallow Bear",
    "sap":{
      "koh":0.1946,
      "naoh":0.139
    },
    "oilProperties":{
      "iodine":92,
      "ins":100,
      "lauric":0,
      "myristic":2,
      "palmitic":7,
      "stearic":3,
      "ricinoleic":0,
      "oleic":70,
      "linoleic":9,
      "linolenic":0
    }
  },
  {
    "id":137,
    "name":"Tallow Beef",
    "sap":{
      "koh":0.2,
      "naoh":0.143
    },
    "oilProperties":{
      "iodine":45,
      "ins":147,
      "lauric":2,
      "myristic":6,
      "palmitic":28,
      "stearic":22,
      "ricinoleic":0,
      "oleic":36,
      "linoleic":3,
      "linolenic":1
    }
  },
  {
    "id":138,
    "name":"Tallow Deer",
    "sap":{
      "koh":0.193,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":31,
      "ins":166,
      "lauric":0,
      "myristic":1,
      "palmitic":20,
      "stearic":24,
      "ricinoleic":0,
      "oleic":30,
      "linoleic":15,
      "linolenic":3
    }
  },
  {
    "id":139,
    "name":"Tallow Goat",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":40,
      "ins":152,
      "lauric":5,
      "myristic":11,
      "palmitic":23,
      "stearic":30,
      "ricinoleic":0,
      "oleic":29,
      "linoleic":2,
      "linolenic":0
    }
  },
  {
    "id":140,
    "name":"Tallow Sheep",
    "sap":{
      "koh":0.194,
      "naoh":0.138
    },
    "oilProperties":{
      "iodine":54,
      "ins":156,
      "lauric":4,
      "myristic":10,
      "palmitic":24,
      "stearic":13,
      "ricinoleic":0,
      "oleic":26,
      "linoleic":5,
      "linolenic":0
    }
  },
  {
    "id":141,
    "name":"Tamanu Oil, kamani",
    "sap":{
      "koh":0.208,
      "naoh":0.148
    },
    "oilProperties":{
      "iodine":111,
      "ins":82,
      "lauric":0,
      "myristic":0,
      "palmitic":12,
      "stearic":13,
      "ricinoleic":0,
      "oleic":34,
      "linoleic":38,
      "linolenic":1
    }
  },
  {
    "id":142,
    "name":"Tucuma Seed Butter",
    "sap":{
      "koh":0.238,
      "naoh":0.17
    },
    "oilProperties":{
      "iodine":13,
      "ins":175,
      "lauric":48,
      "myristic":23,
      "palmitic":6,
      "stearic":0,
      "ricinoleic":0,
      "oleic":13,
      "linoleic":0,
      "linolenic":0
    }
  },
  {
    "id":143,
    "name":"Ucuuba Butter",
    "sap":{
      "koh":0.205,
      "naoh":0.146
    },
    "oilProperties":{
      "iodine":38,
      "ins":167,
      "lauric":0,
      "myristic":0,
      "palmitic":0,
      "stearic":31,
      "ricinoleic":0,
      "oleic":44,
      "linoleic":5,
      "linolenic":0
    }
  },
  {
    "id":144,
    "name":"Walmart GV Shortening, tallow, palm",
    "sap":{
      "koh":0.198,
      "naoh":0.141
    },
    "oilProperties":{
      "iodine":49,
      "ins":151,
      "lauric":1,
      "myristic":4,
      "palmitic":35,
      "stearic":14,
      "ricinoleic":0,
      "oleic":37,
      "linoleic":6,
      "linolenic":1
    }
  },
  {
    "id":145,
    "name":"Walnut Oil",
    "sap":{
      "koh":0.189,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":145,
      "ins":45,
      "lauric":0,
      "myristic":0,
      "palmitic":7,
      "stearic":2,
      "ricinoleic":0,
      "oleic":18,
      "linoleic":60,
      "linolenic":0
    }
  },
  {
    "id":146,
    "name":"Watermelon Seed Oil",
    "sap":{
      "koh":0.19,
      "naoh":0.135
    },
    "oilProperties":{
      "iodine":119,
      "ins":71,
      "lauric":0,
      "myristic":0,
      "palmitic":11,
      "stearic":10,
      "ricinoleic":0,
      "oleic":18,
      "linoleic":60,
      "linolenic":1
    }
  },
  {
    "id":147,
    "name":"Wheat Germ Oil",
    "sap":{
      "koh":0.183,
      "naoh":0.13
    },
    "oilProperties":{
      "iodine":128,
      "ins":58,
      "lauric":0,
      "myristic":0,
      "palmitic":17,
      "stearic":2,
      "ricinoleic":0,
      "oleic":17,
      "linoleic":58,
      "linolenic":0
    }
  },
  {
    "id":148,
    "name":"Yangu, cape chestnut",
    "sap":{
      "koh":0.192,
      "naoh":0.137
    },
    "oilProperties":{
      "iodine":95,
      "ins":97,
      "lauric":0,
      "myristic":0,
      "palmitic":18,
      "stearic":5,
      "ricinoleic":0,
      "oleic":45,
      "linoleic":30,
      "linolenic":1
    }
  },
  {
    "id":149,
    "name":"Zapote seed oil, (Aceite de Sapuyul or Mamey)",
    "sap":{
      "koh":0.188,
      "naoh":0.134
    },
    "oilProperties":{
      "iodine":72,
      "ins":116,
      "lauric":0,
      "myristic":0,
      "palmitic":9,
      "stearic":21,
      "ricinoleic":0,
      "oleic":52,
      "linoleic":13,
      "linolenic":0
    }
  }
];

const setup = {
  purity: {
    naoh: 0.97,
    koh: 0.90,
  },
  superfatPercent: 0.0,
  waterPercent: 0.33
};
